# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from api_provider_management.models.api_provider_func_role_any_of import ApiProviderFuncRoleAnyOf


class ApiProviderFuncRole(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ApiProviderFuncRole - a model defined in OpenAPI

    """


ApiProviderFuncRole.update_forward_refs()
