# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from api_provider_management.models.api_provider_function_details import APIProviderFunctionDetails


class APIProviderEnrolmentDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    APIProviderEnrolmentDetails - a model defined in OpenAPI

        api_prov_dom_id: The api_prov_dom_id of this APIProviderEnrolmentDetails [Optional].
        reg_sec: The reg_sec of this APIProviderEnrolmentDetails.
        api_prov_funcs: The api_prov_funcs of this APIProviderEnrolmentDetails [Optional].
        api_prov_dom_info: The api_prov_dom_info of this APIProviderEnrolmentDetails [Optional].
        supp_feat: The supp_feat of this APIProviderEnrolmentDetails [Optional].
        fail_reason: The fail_reason of this APIProviderEnrolmentDetails [Optional].
    """

    api_prov_dom_id: Optional[str] = None
    reg_sec: str
    api_prov_funcs: Optional[List[APIProviderFunctionDetails]] = None
    api_prov_dom_info: Optional[str] = None
    supp_feat: Optional[str] = None
    fail_reason: Optional[str] = None

    @validator("supp_feat")
    def supp_feat_pattern(cls, value):
        assert value is not None and re.match(r"^[A-Fa-f0-9]*$", value)
        return value

APIProviderEnrolmentDetails.update_forward_refs()
