# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from access_control_policy.models.api_invoker_policy import ApiInvokerPolicy


class AccessControlPolicyList(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccessControlPolicyList - a model defined in OpenAPI

        api_invoker_policies: The api_invoker_policies of this AccessControlPolicyList [Optional].
    """

    api_invoker_policies: Optional[List[ApiInvokerPolicy]] = None

AccessControlPolicyList.update_forward_refs()
