# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from access_control_policy.models.time_range_list import TimeRangeList


class ApiInvokerPolicy(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ApiInvokerPolicy - a model defined in OpenAPI

        api_invoker_id: The api_invoker_id of this ApiInvokerPolicy.
        allowed_total_invocations: The allowed_total_invocations of this ApiInvokerPolicy [Optional].
        allowed_invocations_per_second: The allowed_invocations_per_second of this ApiInvokerPolicy [Optional].
        allowed_invocation_time_range_list: The allowed_invocation_time_range_list of this ApiInvokerPolicy [Optional].
    """

    api_invoker_id: str
    allowed_total_invocations: Optional[int] = None
    allowed_invocations_per_second: Optional[int] = None
    allowed_invocation_time_range_list: Optional[List[TimeRangeList]] = None

ApiInvokerPolicy.update_forward_refs()
