# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api_provider_management.models.base_model_ import Model
from api_provider_management.models.api_provider_func_role_any_of import ApiProviderFuncRoleAnyOf
from api_provider_management import util

from api_provider_management.models.api_provider_func_role_any_of import ApiProviderFuncRoleAnyOf  # noqa: E501

class ApiProviderFuncRole(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """ApiProviderFuncRole - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProviderFuncRole':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiProviderFuncRole of this ApiProviderFuncRole.  # noqa: E501
        :rtype: ApiProviderFuncRole
        """
        return util.deserialize_model(dikt, cls)
