# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api_invoker_management.models.base_model_ import Model
from api_invoker_management import util


class OperationAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    PATCH = "PATCH"
    DELETE = "DELETE"
    def __init__(self):  # noqa: E501
        """OperationAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OperationAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Operation_anyOf of this OperationAnyOf.  # noqa: E501
        :rtype: OperationAnyOf
        """
        return util.deserialize_model(dikt, cls)
