# coding: utf-8

"""
    CAPIF_Routing_Info_API

    API for Routing information. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

    The version of the OpenAPI document: 1.1.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from capif_routing_info.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="CAPIF_Routing_Info_API",
    description="API for Routing information. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. ",
    version="1.1.0-alpha.1",
)

app.include_router(DefaultApiRouter)
