# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api_provider_management.models.base_model_ import Model
from api_provider_management import util


class ApiProviderFuncRoleAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AEF = "AEF"
    APF = "APF"
    AMF = "AMF"
    def __init__(self):  # noqa: E501
        """ApiProviderFuncRoleAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ApiProviderFuncRoleAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiProviderFuncRole_anyOf of this ApiProviderFuncRoleAnyOf.  # noqa: E501
        :rtype: ApiProviderFuncRoleAnyOf
        """
        return util.deserialize_model(dikt, cls)
