services:
  aef-security:
    build: TS29222_AEF_Security_API/.
    expose:
      - "8080"
  api-invoker-management:
    build: TS29222_CAPIF_API_Invoker_Management_API/.
    expose:
      - "8080"
  api-provider-management:
    build: TS29222_CAPIF_API_Provider_Management_API/.
    expose:
      - "8080"
  access-control-policy:
    build: TS29222_CAPIF_Access_Control_Policy_API/.
    expose:
      - "8080"
  logs:
    build: TS29222_CAPIF_Auditing_API/.
    expose:
      - "8080"
  service-apis:
    build: TS29222_CAPIF_Discover_Service_API/.
    expose:
      - "8080"
  capif-events:
    build: TS29222_CAPIF_Events_API/.
    expose:
      - "8080"
  api-invocation-logs:
    build: TS29222_CAPIF_Logging_API_Invocation_API/.
    expose:
      - "8080"
  published-apis:
    build: TS29222_CAPIF_Publish_Service_API/.
    expose:
      - "8080"
  capif-routing-info:
    build: TS29222_CAPIF_Routing_Info_API/.
    expose:
      - "8080"
  capif-security:
    build: TS29222_CAPIF_Security_API/.
    expose:
      - "8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - aef-security
      - api-invoker-management
      - api-provider-management
      - access-control-policy
      - logs
      - service-apis
      - capif-events
      - api-invocation-logs
      - published-apis
      - capif-routing-info
      - capif-security
