# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from capif_events.models.base_model_ import Model
from capif_events import util


class AccessControlPolicyListExtAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_id=None):  # noqa: E501
        """AccessControlPolicyListExtAllOf - a model defined in OpenAPI

        :param api_id: The api_id of this AccessControlPolicyListExtAllOf.  # noqa: E501
        :type api_id: str
        """
        self.openapi_types = {
            'api_id': str
        }

        self.attribute_map = {
            'api_id': 'apiId'
        }

        self._api_id = api_id

    @classmethod
    def from_dict(cls, dikt) -> 'AccessControlPolicyListExtAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccessControlPolicyListExt_allOf of this AccessControlPolicyListExtAllOf.  # noqa: E501
        :rtype: AccessControlPolicyListExtAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_id(self):
        """Gets the api_id of this AccessControlPolicyListExtAllOf.


        :return: The api_id of this AccessControlPolicyListExtAllOf.
        :rtype: str
        """
        return self._api_id

    @api_id.setter
    def api_id(self, api_id):
        """Sets the api_id of this AccessControlPolicyListExtAllOf.


        :param api_id: The api_id of this AccessControlPolicyListExtAllOf.
        :type api_id: str
        """

        self._api_id = api_id
