# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from capif_events.models.base_model_ import Model
from capif_events.models.notification_flag_any_of import NotificationFlagAnyOf
from capif_events import util

from capif_events.models.notification_flag_any_of import NotificationFlagAnyOf  # noqa: E501

class NotificationFlag(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """NotificationFlag - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'NotificationFlag':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotificationFlag of this NotificationFlag.  # noqa: E501
        :rtype: NotificationFlag
        """
        return util.deserialize_model(dikt, cls)
