# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_events.models.access_control_policy_list import AccessControlPolicyList
from capif_events.models.access_control_policy_list_ext_all_of import AccessControlPolicyListExtAllOf
from capif_events.models.api_invoker_policy import ApiInvokerPolicy


class AccessControlPolicyListExt(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccessControlPolicyListExt - a model defined in OpenAPI

        api_invoker_policies: The api_invoker_policies of this AccessControlPolicyListExt [Optional].
        api_id: The api_id of this AccessControlPolicyListExt.
    """

    api_invoker_policies: Optional[List[ApiInvokerPolicy]] = None
    api_id: str

AccessControlPolicyListExt.update_forward_refs()
