# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class AccessControlPolicyListExtAllOf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccessControlPolicyListExtAllOf - a model defined in OpenAPI

        api_id: The api_id of this AccessControlPolicyListExtAllOf [Optional].
    """

    api_id: Optional[str] = None

AccessControlPolicyListExtAllOf.update_forward_refs()
