# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_events.models.data_format import DataFormat
from capif_events.models.interface_description import InterfaceDescription
from capif_events.models.protocol import Protocol
from capif_events.models.security_method import SecurityMethod
from capif_events.models.version import Version


class AefProfile(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AefProfile - a model defined in OpenAPI

        aef_id: The aef_id of this AefProfile.
        versions: The versions of this AefProfile.
        protocol: The protocol of this AefProfile [Optional].
        data_format: The data_format of this AefProfile [Optional].
        security_methods: The security_methods of this AefProfile [Optional].
        domain_name: The domain_name of this AefProfile [Optional].
        interface_descriptions: The interface_descriptions of this AefProfile [Optional].
    """

    aef_id: str
    versions: List[Version]
    protocol: Optional[Protocol] = None
    data_format: Optional[DataFormat] = None
    security_methods: Optional[List[SecurityMethod]] = None
    domain_name: Optional[str] = None
    interface_descriptions: Optional[List[InterfaceDescription]] = None

AefProfile.update_forward_refs()
