# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_events.models.access_control_policy_list_ext import AccessControlPolicyListExt
from capif_events.models.invocation_log import InvocationLog
from capif_events.models.service_api_description import ServiceAPIDescription
from capif_events.models.topology_hiding import TopologyHiding


class CAPIFEventDetail(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CAPIFEventDetail - a model defined in OpenAPI

        service_api_descriptions: The service_api_descriptions of this CAPIFEventDetail [Optional].
        api_ids: The api_ids of this CAPIFEventDetail [Optional].
        api_invoker_ids: The api_invoker_ids of this CAPIFEventDetail [Optional].
        acc_ctrl_pol_list: The acc_ctrl_pol_list of this CAPIFEventDetail [Optional].
        invocation_logs: The invocation_logs of this CAPIFEventDetail [Optional].
        api_topo_hide: The api_topo_hide of this CAPIFEventDetail [Optional].
    """

    service_api_descriptions: Optional[List[ServiceAPIDescription]] = None
    api_ids: Optional[List[str]] = None
    api_invoker_ids: Optional[List[str]] = None
    acc_ctrl_pol_list: Optional[AccessControlPolicyListExt] = None
    invocation_logs: Optional[List[InvocationLog]] = None
    api_topo_hide: Optional[TopologyHiding] = None

CAPIFEventDetail.update_forward_refs()
