# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class CAPIFEventFilter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CAPIFEventFilter - a model defined in OpenAPI

        api_ids: The api_ids of this CAPIFEventFilter [Optional].
        api_invoker_ids: The api_invoker_ids of this CAPIFEventFilter [Optional].
        aef_ids: The aef_ids of this CAPIFEventFilter [Optional].
    """

    api_ids: Optional[List[str]] = None
    api_invoker_ids: Optional[List[str]] = None
    aef_ids: Optional[List[str]] = None

CAPIFEventFilter.update_forward_refs()
