# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_events.models.capif_event import CAPIFEvent
from capif_events.models.capif_event_detail import CAPIFEventDetail


class EventNotification(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EventNotification - a model defined in OpenAPI

        subscription_id: The subscription_id of this EventNotification.
        events: The events of this EventNotification.
        event_detail: The event_detail of this EventNotification [Optional].
    """

    subscription_id: str
    events: CAPIFEvent
    event_detail: Optional[CAPIFEventDetail] = None

EventNotification.update_forward_refs()
