# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_events.models.log import Log


class InvocationLog(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    InvocationLog - a model defined in OpenAPI

        aef_id: The aef_id of this InvocationLog.
        api_invoker_id: The api_invoker_id of this InvocationLog.
        logs: The logs of this InvocationLog.
        supported_features: The supported_features of this InvocationLog [Optional].
    """

    aef_id: str
    api_invoker_id: str
    logs: List[Log]
    supported_features: Optional[str] = None

    @validator("supported_features")
    def supported_features_pattern(cls, value):
        assert value is not None and re.match(r"^[A-Fa-f0-9]*$", value)
        return value

InvocationLog.update_forward_refs()
