# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_events.models.communication_type import CommunicationType
from capif_events.models.operation import Operation


class Resource(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Resource - a model defined in OpenAPI

        resource_name: The resource_name of this Resource.
        comm_type: The comm_type of this Resource.
        uri: The uri of this Resource.
        cust_op_name: The cust_op_name of this Resource [Optional].
        operations: The operations of this Resource [Optional].
        description: The description of this Resource [Optional].
    """

    resource_name: str
    comm_type: CommunicationType
    uri: str
    cust_op_name: Optional[str] = None
    operations: Optional[List[Operation]] = None
    description: Optional[str] = None

Resource.update_forward_refs()
