# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_events.models.aef_profile import AefProfile
from capif_events.models.ipv4_address_range import Ipv4AddressRange
from capif_events.models.ipv6_address_range import Ipv6AddressRange


class RoutingRule(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RoutingRule - a model defined in OpenAPI

        ipv4_addr_ranges: The ipv4_addr_ranges of this RoutingRule [Optional].
        ipv6_addr_ranges: The ipv6_addr_ranges of this RoutingRule [Optional].
        aef_profile: The aef_profile of this RoutingRule.
    """

    ipv4_addr_ranges: Optional[List[Ipv4AddressRange]] = None
    ipv6_addr_ranges: Optional[List[Ipv6AddressRange]] = None
    aef_profile: AefProfile

RoutingRule.update_forward_refs()
