# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class WebsockNotifConfig(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    WebsockNotifConfig - a model defined in OpenAPI

        websocket_uri: The websocket_uri of this WebsockNotifConfig [Optional].
        request_websocket_uri: The request_websocket_uri of this WebsockNotifConfig [Optional].
    """

    websocket_uri: Optional[str] = None
    request_websocket_uri: Optional[bool] = None

WebsockNotifConfig.update_forward_refs()
