env: "kubernetes-athens"

ingress_ip: 
    athens: "10.161.1.117"
    uma: "x.x.x.x"

apiInvocationLogs:
  apiInvocationLogs:
    env:
      capifHostname: "my-capif.evolved-5g.eu"
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_api-invocation-logs_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
apiInvokerManagement:
  apiInvokerManagement:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_api-invoker-management_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
apiProviderManagement:
  apiProviderManagement:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_api-provider-management_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
capifEvents:
  capifEvents:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_capif-events_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
capifRoutingInfo:
  capifRoutingInfo:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_capif-routing-info_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
capifSecurity:
  capifSecurity:
    env:
      capifHostname: "my-capif.evolved-5g.eu"
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_capif-security_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
easyRsa:
  easyRsa:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_easy-rsa_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
jwtauth:
  jwtauth:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_jwtauth_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
logs:
  logs:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_logs_1"
      tag: ""
    resources:
     limits:
       cpu: 100m
       memory: 128Mi
     requests:
       cpu: 100m
       memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
mongo:
  mongo:
    env:
      mongoInitdbRootPassword: example
      mongoInitdbRootUsername: root
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_mongo_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  replicas: 1
  type: ClusterIP
mongoExpress:
  mongoExpress:
    env:
      meConfigMongodbAdminpassword: example
      meConfigMongodbAdminusername: root
      meConfigMongodbUrl: mongodb://root:example@mongo:27017/
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_mongo-express_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8081
  replicas: 1
  type: ClusterIP
nginx:
  nginx:
    env:
      capifHostname: "my-capif.evolved-5g.eu"
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_nginx_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 443
  replicas: 1
  type: ClusterIP
publishedApis:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  publishedApis:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_published-apis_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  replicas: 1
  type: ClusterIP
redis:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  redis:
    env:
      redisReplicationMode: master
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_redis_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  replicas: 1
  type: ClusterIP
serviceApis:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  replicas: 1
  serviceApis:
    image:
      repository: "709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:capif-services_service-apis_1"
      tag: ""
    resources:
     cpu: 100m
     memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  type: ClusterIP
