# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from api_invoker_management.models.onboarding_information import OnboardingInformation
from api_invoker_management.models.service_api_description import ServiceAPIDescription
from api_invoker_management.models.websock_notif_config import WebsockNotifConfig


class APIInvokerEnrolmentDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    APIInvokerEnrolmentDetails - a model defined in OpenAPI

        api_invoker_id: The api_invoker_id of this APIInvokerEnrolmentDetails [Optional].
        onboarding_information: The onboarding_information of this APIInvokerEnrolmentDetails.
        notification_destination: The notification_destination of this APIInvokerEnrolmentDetails.
        request_test_notification: The request_test_notification of this APIInvokerEnrolmentDetails [Optional].
        websock_notif_config: The websock_notif_config of this APIInvokerEnrolmentDetails [Optional].
        api_list: The api_list of this APIInvokerEnrolmentDetails [Optional].
        api_invoker_information: The api_invoker_information of this APIInvokerEnrolmentDetails [Optional].
        supported_features: The supported_features of this APIInvokerEnrolmentDetails [Optional].
    """

    api_invoker_id: Optional[str] = None
    onboarding_information: OnboardingInformation
    notification_destination: str
    request_test_notification: Optional[bool] = None
    websock_notif_config: Optional[WebsockNotifConfig] = None
    api_list: Optional[List[ServiceAPIDescription]] = None
    api_invoker_information: Optional[str] = None
    supported_features: Optional[str] = None

    @validator("supported_features")
    def supported_features_pattern(cls, value):
        assert value is not None and re.match(r"^[A-Fa-f0-9]*$", value)
        return value

APIInvokerEnrolmentDetails.update_forward_refs()
