# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from api_invoker_management.models.api_invoker_enrolment_details import APIInvokerEnrolmentDetails
from api_invoker_management.models.service_api_description import ServiceAPIDescription


class OnboardingNotification(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    OnboardingNotification - a model defined in OpenAPI

        result: The result of this OnboardingNotification.
        resource_location: The resource_location of this OnboardingNotification [Optional].
        api_invoker_enrolment_details: The api_invoker_enrolment_details of this OnboardingNotification [Optional].
        api_list: The api_list of this OnboardingNotification [Optional].
    """

    result: bool
    resource_location: Optional[str] = None
    api_invoker_enrolment_details: Optional[APIInvokerEnrolmentDetails] = None
    api_list: Optional[List[ServiceAPIDescription]] = None

OnboardingNotification.update_forward_refs()
