# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class OnboardingInformation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    OnboardingInformation - a model defined in OpenAPI

        api_invoker_public_key: The api_invoker_public_key of this OnboardingInformation.
        api_invoker_certificate: The api_invoker_certificate of this OnboardingInformation [Optional].
        onboarding_secret: The onboarding_secret of this OnboardingInformation [Optional].
    """

    api_invoker_public_key: str
    api_invoker_certificate: Optional[str] = None
    onboarding_secret: Optional[str] = None

OnboardingInformation.update_forward_refs()
