# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class PublishedApiPath(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PublishedApiPath - a model defined in OpenAPI

        ccf_ids: The ccf_ids of this PublishedApiPath [Optional].
    """

    ccf_ids: Optional[List[str]] = None

PublishedApiPath.update_forward_refs()
