# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from published_apis.models.communication_type import CommunicationType
from published_apis.models.operation import Operation


class CustomOperation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CustomOperation - a model defined in OpenAPI

        comm_type: The comm_type of this CustomOperation.
        cust_op_name: The cust_op_name of this CustomOperation.
        operations: The operations of this CustomOperation [Optional].
        description: The description of this CustomOperation [Optional].
    """

    comm_type: CommunicationType
    cust_op_name: str
    operations: Optional[List[Operation]] = None
    description: Optional[str] = None

CustomOperation.update_forward_refs()
