# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class CheckAuthenticationReq(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CheckAuthenticationReq - a model defined in OpenAPI

        api_invoker_id: The api_invoker_id of this CheckAuthenticationReq.
        supported_features: The supported_features of this CheckAuthenticationReq.
    """

    api_invoker_id: str
    supported_features: str

    @validator("supported_features")
    def supported_features_pattern(cls, value):
        assert value is not None and re.match(r"^[A-Fa-f0-9]*$", value)
        return value

CheckAuthenticationReq.update_forward_refs()
