# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from aef_security.models.security_notification import SecurityNotification


class RevokeAuthorizationReq(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RevokeAuthorizationReq - a model defined in OpenAPI

        revoke_info: The revoke_info of this RevokeAuthorizationReq.
        supported_features: The supported_features of this RevokeAuthorizationReq.
    """

    revoke_info: SecurityNotification
    supported_features: str

    @validator("supported_features")
    def supported_features_pattern(cls, value):
        assert value is not None and re.match(r"^[A-Fa-f0-9]*$", value)
        return value

RevokeAuthorizationReq.update_forward_refs()
