# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from aef_security.models.cause import Cause


class SecurityNotification(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SecurityNotification - a model defined in OpenAPI

        api_invoker_id: The api_invoker_id of this SecurityNotification.
        aef_id: The aef_id of this SecurityNotification [Optional].
        api_ids: The api_ids of this SecurityNotification.
        cause: The cause of this SecurityNotification.
    """

    api_invoker_id: str
    aef_id: Optional[str] = None
    api_ids: List[str]
    cause: Cause

SecurityNotification.update_forward_refs()
