# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from capif_security.models.base_model_ import Model
from capif_security import util


class CauseAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    OVERLIMIT_USAGE = "OVERLIMIT_USAGE"
    UNEXPECTED_REASON = "UNEXPECTED_REASON"
    def __init__(self):  # noqa: E501
        """CauseAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CauseAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Cause_anyOf of this CauseAnyOf.  # noqa: E501
        :rtype: CauseAnyOf
        """
        return util.deserialize_model(dikt, cls)
