mongo: {
  'user': 'root',
  'password': 'example',
  'db': 'capif',
  'col': 'eventsdetails',
  'capif_users_col': 'user',
  'host': 'mongo',
  'port': "27017"
}

mqtt: {
  'url': 'mosquitto',
  'port': 1883,
  'username': '',
  'password': '',
  'keepalive': 10,
  'tls': False
}