# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Ipv6AddressRange(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Ipv6AddressRange - a model defined in OpenAPI

        start: The start of this Ipv6AddressRange.
        end: The end of this Ipv6AddressRange.
    """

    start: str
    end: str

Ipv6AddressRange.update_forward_refs()
