# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_routing_info.models.routing_rule import RoutingRule


class RoutingInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RoutingInfo - a model defined in OpenAPI

        routing_rules: The routing_rules of this RoutingInfo.
    """

    routing_rules: List[RoutingRule]

RoutingInfo.update_forward_refs()
