# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_routing_info.models.custom_operation import CustomOperation
from capif_routing_info.models.resource import Resource


class Version(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Version - a model defined in OpenAPI

        api_version: The api_version of this Version.
        expiry: The expiry of this Version [Optional].
        resources: The resources of this Version [Optional].
        cust_operations: The cust_operations of this Version [Optional].
    """

    api_version: str
    expiry: Optional[datetime] = None
    resources: Optional[List[Resource]] = None
    cust_operations: Optional[List[CustomOperation]] = None

Version.update_forward_refs()
