mongo: {
  'user': 'root',
  'password': 'example',
  'db': 'capif',
  'col': 'providerenrolmentdetails',
  'certs_col': "certs",
  'capif_users': 'user',
  'host': 'mongo',
  'port': "27017"
}

ca_factory: {
  "url": "easy-rsa",
  "port": "8083"
}

