services:
  aef-security:
    build: TS29222_AEF_Security_API/.
    expose:
      - "8080"
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:security_api
  api-invoker-management:
    build:
      context: ./TS29222_CAPIF_API_Invoker_Management_API
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_API_Invoker_Management_API:/usr/src/app
    restart: unless-stopped
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:api_invoker_management_api
  api-provider-management:
    build: TS29222_CAPIF_API_Provider_Management_API/.
    expose:
      - "8080"
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:api_provider_management_api
  access-control-policy:
    build: TS29222_CAPIF_Access_Control_Policy_API/.
    expose:
      - "8080"
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:access_control_policy_api
  logs:
    build: TS29222_CAPIF_Auditing_API/.
    expose:
      - "8080"
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:auditing_api
  service-apis:
    build:
      context: ./TS29222_CAPIF_Discover_Service_API
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_Discover_Service_API:/usr/src/app
    restart: unless-stopped
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:discover_service_api
  capif-events:
    build: TS29222_CAPIF_Events_API/.
    expose:
      - "8080"
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:events_api
  api-invocation-logs:
    build: TS29222_CAPIF_Logging_API_Invocation_API/.
    expose:
      - "8080"
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:api_invocation_logs_api
  published-apis:
    build: TS29222_CAPIF_Publish_Service_API/.
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_Publish_Service_API:/usr/src/app
    restart: unless-stopped
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:publish_service_api
  capif-routing-info:
    build: TS29222_CAPIF_Routing_Info_API/.
    expose:
      - "8080"
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:routing_info_api
  capif-security:
    build: TS29222_CAPIF_Security_API/.
    expose:
      - "8080"
    restart: unless-stopped
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:security_api
  jwtauth:
    build:
      context: ./jwt_auth
    expose:
      - "8080"
    volumes:
      - ./jwt_auth:/usr/src/app
    restart: unless-stopped
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:jwtauth
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
  nginx:
    build: nginx/.
    ports:
      - "8080:8080"
    image: 709233559969.dkr.ecr.eu-central-1.amazonaws.com/evolved5g:nginx
    depends_on:
      - aef-security
      - api-invoker-management
      - api-provider-management
      - access-control-policy
      - service-apis
      - api-invocation-logs
      - published-apis
      - capif-routing-info
      - capif-security