apiVersion: 1

providers:

  - name: Default # A uniquely identifiable name for the provider
    orgId: 1
    folder: "" # The folder where to place the dashboards
    folderUid: ""
    type: file
    disableDeletion: false
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards

