# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class AccessTokenErr(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccessTokenErr - a model defined in OpenAPI

        error: The error of this AccessTokenErr.
        error_description: The error_description of this AccessTokenErr [Optional].
        error_uri: The error_uri of this AccessTokenErr [Optional].
    """

    error: str
    error_description: Optional[str] = None
    error_uri: Optional[str] = None

AccessTokenErr.update_forward_refs()
