# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class AccessTokenClaims(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccessTokenClaims - a model defined in OpenAPI

        iss: The iss of this AccessTokenClaims.
        scope: The scope of this AccessTokenClaims.
        exp: The exp of this AccessTokenClaims.
    """

    iss: str
    scope: str
    exp: int

    @validator("exp")
    def exp_min(cls, value):
        assert value >= 0
        return value

AccessTokenClaims.update_forward_refs()
