# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class AccessTokenRsp(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccessTokenRsp - a model defined in OpenAPI

        access_token: The access_token of this AccessTokenRsp.
        token_type: The token_type of this AccessTokenRsp.
        expires_in: The expires_in of this AccessTokenRsp.
        scope: The scope of this AccessTokenRsp [Optional].
    """

    access_token: str
    token_type: str
    expires_in: int
    scope: Optional[str] = None

    @validator("expires_in")
    def expires_in_min(cls, value):
        assert value >= 0
        return value

AccessTokenRsp.update_forward_refs()
