# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from capif_security.models.interface_description import InterfaceDescription
from capif_security.models.security_method import SecurityMethod


class SecurityInformation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SecurityInformation - a model defined in OpenAPI

        interface_details: The interface_details of this SecurityInformation [Optional].
        aef_id: The aef_id of this SecurityInformation [Optional].
        pref_security_methods: The pref_security_methods of this SecurityInformation.
        sel_security_method: The sel_security_method of this SecurityInformation [Optional].
        authentication_info: The authentication_info of this SecurityInformation [Optional].
        authorization_info: The authorization_info of this SecurityInformation [Optional].
    """

    interface_details: Optional[InterfaceDescription] = None
    aef_id: Optional[str] = None
    pref_security_methods: List[SecurityMethod]
    sel_security_method: Optional[SecurityMethod] = None
    authentication_info: Optional[str] = None
    authorization_info: Optional[str] = None

SecurityInformation.update_forward_refs()
