# coding: utf-8

"""
    AEF_Security_API

    API for AEF security management. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from aef_security.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="AEF_Security_API",
    description="API for AEF security management. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. ",
    version="1.2.0-alpha.1",
)

app.include_router(DefaultApiRouter)
