# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from published_apis.models.base_model_ import Model
from published_apis import util


class CommunicationTypeAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    REQUEST_RESPONSE = "REQUEST_RESPONSE"
    SUBSCRIBE_NOTIFY = "SUBSCRIBE_NOTIFY"
    def __init__(self):  # noqa: E501
        """CommunicationTypeAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CommunicationTypeAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunicationType_anyOf of this CommunicationTypeAnyOf.  # noqa: E501
        :rtype: CommunicationTypeAnyOf
        """
        return util.deserialize_model(dikt, cls)
