# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from published_apis.models.base_model_ import Model
from published_apis import util


class DataFormatAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    JSON = "JSON"
    def __init__(self):  # noqa: E501
        """DataFormatAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DataFormatAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataFormat_anyOf of this DataFormatAnyOf.  # noqa: E501
        :rtype: DataFormatAnyOf
        """
        return util.deserialize_model(dikt, cls)
