# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from access_control_policy.models.base_model_ import Model
from access_control_policy.models.api_invoker_policy import ApiInvokerPolicy
from access_control_policy import util

from access_control_policy.models.api_invoker_policy import ApiInvokerPolicy  # noqa: E501

class AccessControlPolicyList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_invoker_policies=None):  # noqa: E501
        """AccessControlPolicyList - a model defined in OpenAPI

        :param api_invoker_policies: The api_invoker_policies of this AccessControlPolicyList.  # noqa: E501
        :type api_invoker_policies: List[ApiInvokerPolicy]
        """
        self.openapi_types = {
            'api_invoker_policies': List[ApiInvokerPolicy]
        }

        self.attribute_map = {
            'api_invoker_policies': 'apiInvokerPolicies'
        }

        self._api_invoker_policies = api_invoker_policies

    @classmethod
    def from_dict(cls, dikt) -> 'AccessControlPolicyList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccessControlPolicyList of this AccessControlPolicyList.  # noqa: E501
        :rtype: AccessControlPolicyList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_invoker_policies(self):
        """Gets the api_invoker_policies of this AccessControlPolicyList.

        Policy of each API invoker.  # noqa: E501

        :return: The api_invoker_policies of this AccessControlPolicyList.
        :rtype: List[ApiInvokerPolicy]
        """
        return self._api_invoker_policies

    @api_invoker_policies.setter
    def api_invoker_policies(self, api_invoker_policies):
        """Sets the api_invoker_policies of this AccessControlPolicyList.

        Policy of each API invoker.  # noqa: E501

        :param api_invoker_policies: The api_invoker_policies of this AccessControlPolicyList.
        :type api_invoker_policies: List[ApiInvokerPolicy]
        """
        if api_invoker_policies is not None and len(api_invoker_policies) < 0:
            raise ValueError("Invalid value for `api_invoker_policies`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._api_invoker_policies = api_invoker_policies
