# coding: utf-8

"""
    CAPIF_API_Invoker_Management_API

    API for API invoker management. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.2
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from api_invoker_management.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="CAPIF_API_Invoker_Management_API",
    description="API for API invoker management. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. ",
    version="1.2.0-alpha.2",
)

app.include_router(DefaultApiRouter)
