# coding: utf-8

"""
    CAPIF_API_Provider_Management_API

    API for API provider domain functions management. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

    The version of the OpenAPI document: 1.1.0-alpha.2
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from api_provider_management.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="CAPIF_API_Provider_Management_API",
    description="API for API provider domain functions management. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. ",
    version="1.1.0-alpha.2",
)

app.include_router(DefaultApiRouter)
