# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from published_apis.models.base_model_ import Model
from published_apis.models.protocol_any_of import ProtocolAnyOf
from published_apis import util

from published_apis.models.protocol_any_of import ProtocolAnyOf  # noqa: E501

class Protocol(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """Protocol - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Protocol':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Protocol of this Protocol.  # noqa: E501
        :rtype: Protocol
        """
        return util.deserialize_model(dikt, cls)
