# coding: utf-8

"""
    CAPIF_Access_Control_Policy_API

    API for access control policy. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from access_control_policy.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="CAPIF_Access_Control_Policy_API",
    description="API for access control policy. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. ",
    version="1.2.0-alpha.1",
)

app.include_router(DefaultApiRouter)
