# coding: utf-8

"""
    CAPIF_Logging_API_Invocation_API

    API for invocation logs. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.1
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from api_invocation_logs.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="CAPIF_Logging_API_Invocation_API",
    description="API for invocation logs. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. ",
    version="1.2.0-alpha.1",
)

app.include_router(DefaultApiRouter)
