# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from capif_routing_info.models.base_model_ import Model
from capif_routing_info.models.communication_type_any_of import CommunicationTypeAnyOf
from capif_routing_info import util

from capif_routing_info.models.communication_type_any_of import CommunicationTypeAnyOf  # noqa: E501

class CommunicationType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """CommunicationType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CommunicationType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunicationType of this CommunicationType.  # noqa: E501
        :rtype: CommunicationType
        """
        return util.deserialize_model(dikt, cls)
