# coding: utf-8

"""
    CAPIF_Publish_Service_API

    API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

    The version of the OpenAPI document: 1.2.0-alpha.2
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from published_apis.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="CAPIF_Publish_Service_API",
    description="API for publishing service APIs. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. ",
    version="1.2.0-alpha.2",
)

app.include_router(DefaultApiRouter)
